# Generated by Django 5.2.1 on 2025-06-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_book_book_id_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='book_cover',
            field=models.ImageField(blank=True, null=True, upload_to='donations/covers/'),
        ),
    ]
