# Generated by Django 5.2.1 on 2025-06-08 16:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_donation_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donate_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
