# Generated by Django 5.2.1 on 2025-06-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_donation_donate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='book_id_isbn',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='recycle',
            name='book_id_isbn',
            field=models.CharField(max_length=20),
        ),
    ]
