# Generated by Django 5.2.1 on 2025-06-08 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_donation_book_id_isbn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='donation_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_books', to='core.donation'),
        ),
        migrations.AddField(
            model_name='book',
            name='is_from_donation',
            field=models.BooleanField(default=False),
        ),
    ]
