# Generated by Django 5.2.1 on 2025-06-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_book_donation_source_book_is_from_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='recycle',
            name='disposal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recycle',
            name='disposal_method',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recycle',
            name='disposal_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recycle',
            name='estimated_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='recycle',
            name='recycling_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='recycle',
            name='status',
            field=models.CharField(choices=[('pending', 'Awaiting Disposal'), ('disposed', 'Disposed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
