# Generated by Django 5.2.1 on 2025-06-09 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_recycle_disposal_date_recycle_disposal_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recycle',
            name='estimated_value',
        ),
        migrations.RemoveField(
            model_name='recycle',
            name='recycling_cost',
        ),
    ]
