# Generated by Django 5.2.1 on 2025-06-10 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_recycle_financial_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipment',
        ),
    ]
