# Generated by Django 5.2.1 on 2025-06-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_management', '0002_remove_room_hourly_rate_remove_roommaintenance_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Hourly rate for booking this room', max_digits=6),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total cost for this booking', max_digits=8),
        ),
    ]
