# Generated by Django 5.2.1 on 2025-06-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_management', '0004_remove_money_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommaintenance',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Maintenance cost', max_digits=10),
        ),
    ]
