# Generated by Django 5.2.1 on 2025-06-07 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('room_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('borrow_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_borrow', models.DateField(auto_now_add=True)),
                ('date_due', models.DateField()),
                ('date_return', models.DateField(blank=True, null=True)),
                ('is_returned', models.BooleanField(default=False)),
                ('renewal_count', models.PositiveIntegerField(default=0)),
                ('max_renewals', models.PositiveIntegerField(default=2)),
                ('notes', models.TextField(blank=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_set', to='core.book')),
                ('borrowed_by_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books_borrowed_for_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_borrow'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('age', models.PositiveIntegerField()),
                ('date_of_birth', models.DateField()),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_books', models.PositiveIntegerField(default=3)),
                ('max_reservations', models.PositiveIntegerField(default=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('fine_id', models.AutoField(primary_key=True, serialize=False)),
                ('fine_type', models.CharField(choices=[('overdue', 'Overdue Book'), ('damage', 'Book Damage'), ('lost', 'Lost Book'), ('late_return', 'Late Return')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('date_imposed', models.DateField(auto_now_add=True)),
                ('date_paid', models.DateField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('borrow_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.borrow')),
                ('imposed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fines_imposed', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='student.member')),
            ],
            options={
                'ordering': ['-date_imposed'],
            },
        ),
        migrations.AddField(
            model_name='borrow',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowings', to='student.member'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_reserved', models.DateField(auto_now_add=True)),
                ('date_expires', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_set', to='core.book')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='student.member')),
            ],
            options={
                'ordering': ['-date_reserved'],
            },
        ),
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('purpose', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('date_booked', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_bookings', to='student.member')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_bookings', to='room_management.room')),
            ],
            options={
                'ordering': ['-booking_date', '-start_time'],
                'constraints': [models.UniqueConstraint(fields=('room', 'booking_date', 'start_time'), name='unique_room_booking_time')],
            },
        ),
    ]
