# Generated by Django 5.2.1 on 2025-06-07 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('book_due', 'Book Due Soon'), ('book_overdue', 'Book Overdue'), ('reservation_ready', 'Reserved Book Available'), ('reservation_expired', 'Reservation Expired'), ('fine_imposed', 'Fine Imposed'), ('room_booking_approved', 'Room Booking Approved'), ('room_booking_cancelled', 'Room Booking Cancelled'), ('general', 'General Notification')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='student.member')),
                ('related_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.book')),
                ('related_room_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.roombooking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
