# Generated by Django 5.2.1 on 2025-06-09 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_recycle_financial_fields'),
        ('room_management', '0003_room_hourly_rate_roombooking_total_cost'),
        ('student', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='related_room_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='room_management.roombooking'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('book_due', 'Book Due Soon'), ('book_overdue', 'Book Overdue'), ('reservation_ready', 'Reserved Book Available'), ('reservation_expired', 'Reservation Expired'), ('fine_imposed', 'Fine Imposed'), ('room_booking_approved', 'Room Booking Approved'), ('room_booking_cancelled', 'Room Booking Cancelled'), ('book_available', 'Book Available'), ('room_available', 'Room Available'), ('general', 'General Notification')], max_length=50),
        ),
        migrations.CreateModel(
            name='BookWaitingList',
            fields=[
                ('waiting_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High Priority'), ('faculty', 'Faculty Priority'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('notified', 'Notified'), ('fulfilled', 'Fulfilled'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('position_in_queue', models.PositiveIntegerField(default=1)),
                ('estimated_availability_date', models.DateField(blank=True, null=True)),
                ('notification_sent_date', models.DateTimeField(blank=True, null=True)),
                ('hold_expires_date', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_list', to='core.book')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_waiting_list', to='student.member')),
            ],
            options={
                'ordering': ['position_in_queue', 'date_joined'],
                'unique_together': {('member', 'book', 'status')},
            },
        ),
        migrations.CreateModel(
            name='RoomBookingQueue',
            fields=[
                ('queue_id', models.AutoField(primary_key=True, serialize=False)),
                ('preferred_date', models.DateField()),
                ('preferred_start_time', models.TimeField()),
                ('preferred_end_time', models.TimeField()),
                ('purpose', models.CharField(max_length=200)),
                ('attendees_count', models.PositiveIntegerField(default=1)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('academic', 'Academic Event'), ('administrative', 'Administrative'), ('emergency', 'Emergency')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('notified', 'Notified'), ('fulfilled', 'Fulfilled'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('position_in_queue', models.PositiveIntegerField(default=1)),
                ('date_joined_queue', models.DateTimeField(auto_now_add=True)),
                ('flexible_date', models.BooleanField(default=False)),
                ('flexible_time', models.BooleanField(default=False)),
                ('date_range_start', models.DateField(blank=True, null=True)),
                ('date_range_end', models.DateField(blank=True, null=True)),
                ('notification_sent_date', models.DateTimeField(blank=True, null=True)),
                ('offer_expires_date', models.DateTimeField(blank=True, null=True)),
                ('offered_date', models.DateField(blank=True, null=True)),
                ('offered_start_time', models.TimeField(blank=True, null=True)),
                ('offered_end_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_queue', to='student.member')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_queue', to='room_management.room')),
            ],
            options={
                'ordering': ['priority', 'position_in_queue', 'date_joined_queue'],
            },
        ),
        migrations.DeleteModel(
            name='RoomBooking',
        ),
    ]
