# Generated by Django 5.2.1 on 2025-06-10 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_notification_related_room_booking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roombookingqueue',
            name='member',
        ),
        migrations.RemoveField(
            model_name='roombookingqueue',
            name='room',
        ),
        migrations.DeleteModel(
            name='BookWaitingList',
        ),
        migrations.DeleteModel(
            name='RoomBookingQueue',
        ),
    ]
