# Generated by Django 5.2.1 on 2025-06-10 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_custom', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminSettings',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
